// examples/react/src/App.jsx
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom'
import { AuthProvider } from './auth/AuthProvider'
import { useAuth } from './auth/AuthContext'
import LoginButton from './components/LoginButton'
import ProtectedRoute from './auth/ProtectedRoute'

// Pages
import Home from './pages/Home'
import Profile from './pages/Profile'
import ApiTest from './pages/ApiTest'
import Callback from './pages/Callback'

import './App.css'

function AppContent() {
  return (
    <div className="app">
      <header>
        <nav className="navbar">
          <div className="nav-brand">
            <h1>React OIDC Demo</h1>
          </div>
          <div className="nav-links">
            <Link to="/">Home</Link>
            <Link to="/profile">Profile</Link>
            <Link to="/api-test">API Test</Link>
          </div>
          <div className="nav-auth">
            <LoginButton />
          </div>
        </nav>
      </header>

      <main className="main-content">
        <Routes>
          <Route path="/" element={<Home />} />
          <Route
            path="/profile"
            element={
              <ProtectedRoute>
                <Profile />
              </ProtectedRoute>
            }
          />
          <Route path="/api-test" element={<ApiTest />} />
          <Route path="/callback" element={<Callback />} />
        </Routes>
      </main>

      <footer>
        <p>React + OIDC Client Demo</p>
      </footer>
    </div>
  )
}

function App() {
  return (
    <Router>
      <AuthProvider>
        <AppContent />
      </AuthProvider>
    </Router>
  )
}

export default App

// examples/vue/src/App.vue
<template>
  <div id="app">
    <header>
      <nav class="navbar">
        <div class="nav-brand">
          <h1>Vue OIDC Demo</h1>
        </div>
        <div class="nav-links">
          <router-link to="/">Home</router-link>
          <router-link to="/profile">Profile</router-link>
          <router-link to="/api-test">API Test</router-link>
        </div>
        <div class="nav-auth">
          <LoginButton />
        </div>
      </nav>
    </header>

    <main class="main-content">
      <router-view />
    </main>

    <footer>
      <p>Vue 3 + OIDC Client Demo</p>
    </footer>
  </div>
</template>

<script setup>
import LoginButton from './components/LoginButton.vue'
</script>

<style scoped>
header {
  background-color: #2c3e50;
  color: white;
  padding: 1rem 0;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.navbar {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 2rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 2rem;
}

.nav-brand h1 {
  font-size: 1.5rem;
  margin: 0;
}

.nav-links {
  display: flex;
  gap: 1.5rem;
  flex: 1;
}

.nav-links a {
  color: white;
  text-decoration: none;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  transition: background-color 0.3s;
}

.nav-links a:hover {
  background-color: rgba(255,255,255,0.1);
}

.nav-links a.router-link-active {
  background-color: rgba(255,255,255,0.2);
}

.main-content {
  max-width: 1200px;
  margin: 2rem auto;
  padding: 0 2rem;
  min-height: calc(100vh - 180px);
}

footer {
  background-color: #f8f9fa;
  padding: 1.5rem;
  text-align: center;
  color: #6c757d;
  margin-top: 2rem;
}

@media (max-width: 768px) {
  .navbar {
    flex-direction: column;
    gap: 1rem;
  }

  .nav-links {
    flex-direction: column;
    width: 100%;
    text-align: center;
  }
}
</style>
