// docs/examples/web/vue/src/Callback.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { userManager } from './auth'

// Step 2: Exchange the auth code for tokens and store the user
const router = useRouter()

onMounted(async () => {
  try {
    await userManager.signinRedirectCallback()
    await router.push('/')
  } catch (err) {
    console.error('Callback error:', err)
  }
})
</script>

<template>
  <p>Completing sign-in...</p>
</template>

// docs/examples/web/react/src/Callback.tsx
import { useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { userManager } from './auth'

// Step 2: Exchange the auth code for tokens and store the user
export default function Callback() {
  const navigate = useNavigate()

  useEffect(() => {
    userManager.signinRedirectCallback()
      .then(() => navigate('/'))
      .catch(console.error)
  }, [navigate])

  return <p>Completing sign-in...</p>
}
